# Language dictionaries for the CSV AI Parser application

# Available languages
LANGUAGES = {
    "pt_BR": {
        "app_title": "🔮 DataVision AI - Análise Inteligente de Dados",
        "app_description": """
        **DataVision AI** é sua plataforma inteligente para análise avançada de dados CSV.
        Transforme seus dados em insights valiosos com o poder da Inteligência Artificial.
        Faça upload de um arquivo CSV e descubra padrões ocultos nos seus dados.
        """,
        "language_selector": "Idioma",
        "file_uploader": "Escolha um arquivo CSV",
        "file_details": "Detalhes do arquivo",
        "filename": "Nome do arquivo",
        "filetype": "Tipo do arquivo",
        "filesize": "Tamanho do arquivo",
        "processing": "Processando seu arquivo CSV... Por favor, aguarde.",
        "error_invalid_file": "Por favor, faça upload de um arquivo CSV válido com a estrutura esperada: 31 colunas incluindo Time, V1-V28, Amount e Class.",
        "success_message": "Arquivo processado com sucesso!",
        "data_preview": "Visualização dos Dados",
        "ask_questions": "Faça Perguntas Sobre Seus Dados",
        "enter_question": "Digite sua pergunta:",
        "question_placeholder": "💬 Pergunte qualquer coisa sobre seus dados: tendências, padrões, estatísticas, correlações...",
        "processing_query": "Processando sua pergunta...",
        "response": "Resposta",
        "additional_insights": "Insights Adicionais",
        "upload_prompt": "Por favor, faça upload de um arquivo CSV para começar.",
        "footer": "Desenvolvido com Google AI e Streamlit | 🔮 DataVision AI",
        "api_key_error": "Por favor, configure sua GEMINI_API_KEY em um arquivo .env",
        "generating_analysis": "Gerando análise inicial... Por favor, aguarde.",
        "analyzing_data": "🧠 Analisando dados para sugestões de gráficos...",
        "graph_error_info": "Por favor, tente um tipo de gráfico diferente ou verifique o formato dos seus dados.",
        "initial_analysis": "Análise Inicial",
        "records_analysis": "Análise de Registros",
        "total_records": "Total de Registros",
        "regular_transactions": "Transações Regulares",
        "fraudulent_transactions": "Transações Fraudulentas",
        "time_analysis": "Análise de Tempo",
        "total_time_period": "Período Total de Tempo",
        "amount_analysis": "Análise de Valores",
        "regular_transactions_heading": "Transações Regulares",
        "fraudulent_transactions_heading": "Transações Fraudulentas",
        "total_amounts": "Valores Totais",
        "min_amount": "Valor Mínimo",
        "max_amount": "Valor Máximo",
        "avg_amount": "Valor Médio",
        "regular_total": "Total Regular",
        "fraudulent_total": "Total Fraudulento",
        "visualization": "Visualização",
        "select_graph": "Selecione um gráfico para exibir:",
        "generate_graph": "Gerar Gráfico",
        "generating_graph": "Gerando gráfico...",
        "fraud_distribution": "Distribuição de Fraudes vs Regulares",
        "amount_distribution": "Distribuição de Valores",
        "time_series": "Transações ao Longo do Tempo",
        "related_questions_warning": "Por favor, faça perguntas relacionadas ao arquivo CSV importado e seus dados.",
        "manual_chart_option": "Ou digite manualmente o tipo de gráfico desejado:",
        "manual_chart_placeholder": "💡 Exemplos: histograma da coluna Amount, gráfico de dispersão entre V1 e V2, mapa de calor de correlação, box plot para outliers...",
        "generate_custom_graph": "Gerar Gráfico Personalizado",
        "custom_chart_validation_error": "Por favor, descreva o tipo de gráfico que você deseja gerar.",
        "download_chart": "📥 Baixar Gráfico",
        "refresh_suggestions": "🔄 Obter Novas Sugestões",
        "getting_new_suggestions": "🔄 Obtendo novas sugestões de IA...",
        "custom_chart_generated": "✅ Gráfico personalizado gerado com sucesso!",
        "help_section_title": "💡 Como usar o DataVision AI",
        "help_step_1": "1️⃣ **Upload**: Faça upload de um arquivo CSV",
        "help_step_2": "2️⃣ **Análise**: Veja insights automáticos gerados pela IA",
        "help_step_3": "3️⃣ **Visualize**: Crie gráficos com sugestões inteligentes",
        "help_step_4": "4️⃣ **Pergunte**: Faça perguntas sobre seus dados em linguagem natural",
        
        # Additional UI elements
        "page_title": "DataVision AI - Análise Inteligente de Dados",
        "settings_title": "⚙️ Configurações",
        "settings_subtitle": "Configure suas preferências",
        "language_help": "Selecione seu idioma preferido",
        "upload_data_title": "📁 Faça Upload dos Seus Dados",
        "upload_data_subtitle": "(Apenas arquivos CSV)",
        "upload_help": "💡 Faça upload de um arquivo CSV para começar a analisar seus dados com IA. Formatos suportados: valores separados por vírgula, ponto e vírgula ou pipe.",
        "file_info_title": "Informações do Arquivo",
        "data_preview_title": "👁️ Visualização dos Dados",
        "data_preview_subtitle": "Primeiras 5 linhas do seu conjunto de dados",
        "ai_analysis_title": "🧠 Análise de IA",
        "ai_analysis_subtitle": "Insights inteligentes sobre seus dados",
        "analysis_in_progress": "🔄 Análise em progresso...",
        "visualization_title": "📊 Visualização de Dados",
        "visualization_subtitle": "Crie gráficos e diagramas",
        "fallback_chart_help": "🤖 Estes gráficos são recomendados pela IA com base nos padrões e estrutura dos seus dados",
        "generate_chart_help": "🚀 Clique para criar sua visualização selecionada",
        "manual_chart_help": "🎨 Descreva o tipo de gráfico que você deseja criar",
        "generate_custom_help": "🎨 Crie uma visualização personalizada baseada na sua descrição",
        "questions_title": "💬 Perguntas e Respostas",
        "questions_subtitle": "Converse com seus dados usando linguagem natural",
        "question_help": "💭 Digite qualquer pergunta sobre seus dados - tendências, padrões, estatísticas...",
        "ai_response_title": "🤖 Resposta da IA",
        "additional_insights_title": "💡 Insights Adicionais",
        "welcome_title": "Bem-vindo ao DataVision AI! 🔮",
        "welcome_subtitle": "Sua plataforma inteligente para análise de dados CSV",
        "welcome_description": "Transforme seus dados em insights valiosos com o poder da Inteligência Artificial.",
        "welcome_step1": "📁 **Faça Upload**: Carregue seu arquivo CSV",
        "welcome_step2": "🧠 **Analise**: Obtenha insights automáticos da IA",
        "welcome_step3": "📊 **Visualize**: Crie gráficos inteligentes",
        "welcome_step4": "💬 **Pergunte**: Converse com seus dados",
        "welcome_cta": "Comece fazendo upload de um arquivo CSV usando o painel lateral!",
        "welcome_ai_title": "IA Inteligente",
        "welcome_ai_description": "Análise automática com insights poderosos",
        "welcome_charts_title": "Gráficos Dinâmicos",
        "welcome_charts_description": "Visualizações interativas e personalizadas",
        "welcome_questions_title": "Perguntas Naturais",
        "welcome_questions_description": "Converse com seus dados em linguagem natural",
        "footer_text": "Desenvolvido com ❤️ usando Google AI e Streamlit | 🔮 DataVision AI",
        "footer_made_with": "Feito com ❤️ para análise inteligente de dados",
        "generate_ai_help": "🚀 Clique para gerar o gráfico selecionado usando IA",
    },
    "en_US": {
        "app_title": "🔮 DataVision AI - Intelligent Data Analysis",
        "app_description": """
        **DataVision AI** is your intelligent platform for advanced CSV data analysis.
        Transform your data into valuable insights with the power of Artificial Intelligence.
        Upload a CSV file and discover hidden patterns in your data.
        """,
        "language_selector": "Language",
        "file_uploader": "Choose a CSV file",
        "file_details": "File Details",
        "filename": "Filename",
        "filetype": "File type",
        "filesize": "File size",
        "processing": "Processing your CSV file... Please wait.",
        "error_invalid_file": "Please upload a valid CSV file with the expected structure: 31 columns including Time, V1-V28, Amount, and Class.",
        "success_message": "File processed successfully!",
        "data_preview": "Data Preview",
        "ask_questions": "Ask Questions About Your Data",
        "enter_question": "Enter your question:",
        "question_placeholder": "💬 Ask anything about your data: trends, patterns, statistics, correlations...",
        "processing_query": "Processing your query...",
        "response": "Response",
        "additional_insights": "Additional Insights",
        "upload_prompt": "Please upload a CSV file to get started.",
        "footer": "Powered by Google AI and Streamlit | 🔮 DataVision AI",
        "api_key_error": "Please set your GEMINI_API_KEY in a .env file",
        "generating_analysis": "Generating initial analysis... Please wait.",
        "analyzing_data": "🧠 Analyzing data for chart suggestions...",
        "graph_error_info": "Please try a different chart type or check your data format.",
        "initial_analysis": "Initial Analysis",
        "records_analysis": "Records Analysis",
        "total_records": "Total Records",
        "regular_transactions": "Regular Transactions",
        "fraudulent_transactions": "Fraudulent Transactions",
        "time_analysis": "Time Analysis",
        "total_time_period": "Total Time Period",
        "amount_analysis": "Amount Analysis",
        "regular_transactions_heading": "Regular Transactions",
        "fraudulent_transactions_heading": "Fraudulent Transactions",
        "total_amounts": "Total Amounts",
        "min_amount": "Minimum Amount",
        "max_amount": "Maximum Amount",
        "avg_amount": "Average Amount",
        "regular_total": "Regular Total",
        "fraudulent_total": "Fraudulent Total",
        "visualization": "Visualization",
        "select_graph": "Select a graph to display:",
        "generate_graph": "Generate Graph",
        "generating_graph": "Generating graph...",
        "fraud_distribution": "Fraud vs Regular Distribution",
        "amount_distribution": "Amount Distribution",
        "time_series": "Transactions Over Time",
        "related_questions_warning": "Please ask questions related to the imported CSV file and its data.",
        "manual_chart_option": "Or manually enter the desired chart type:",
        "manual_chart_placeholder": "💡 Examples: histogram of Amount column, scatter plot between V1 and V2, correlation heatmap, box plot for outliers...",
        "generate_custom_graph": "Generate Custom Graph",
        "custom_chart_validation_error": "Please describe the type of chart you want to generate.",
        "download_chart": "📥 Download Chart",
        "refresh_suggestions": "🔄 Get New Suggestions", 
        "getting_new_suggestions": "🔄 Getting new AI suggestions...",
        "custom_chart_generated": "✅ Custom chart generated successfully!",
        "chart_generation_options": "Chart Generation Options",
        "help_section_title": "💡 How to use DataVision AI",
        "help_step_1": "1️⃣ **Upload**: Upload a CSV file",
        "help_step_2": "2️⃣ **Analyze**: View automatic AI-generated insights",
        "help_step_3": "3️⃣ **Visualize**: Create charts with intelligent suggestions",
        "help_step_4": "4️⃣ **Ask**: Ask questions about your data in natural language",
        
        # Additional UI elements
        "page_title": "DataVision AI - Intelligent Data Analysis",
        "settings_title": "⚙️ Settings",
        "settings_subtitle": "Configure your preferences",
        "language_help": "Select your preferred language",
        "upload_data_title": "📁 Upload Your Data",
        "upload_data_subtitle": "(CSV files only)",
        "upload_help": "💡 Upload a CSV file to start analyzing your data with AI. Supported formats: comma, semicolon, or pipe separated values.",
        "file_info_title": "File Information",
        "data_preview_title": "👁️ Data Preview",
        "data_preview_subtitle": "First 5 rows of your dataset",
        "ai_analysis_title": "🧠 AI Analysis",
        "ai_analysis_subtitle": "Intelligent insights about your data",
        "analysis_in_progress": "🔄 Analysis in progress...",
        "visualization_title": "📊 Data Visualization",
        "visualization_subtitle": "Create charts and graphs",
        "fallback_chart_help": "🤖 These charts are AI-recommended based on your data patterns and structure",
        "generate_chart_help": "🚀 Click to create your selected visualization",
        "manual_chart_help": "🎨 Describe the type of chart you want to create",
        "generate_custom_help": "🎨 Create a custom visualization based on your description",
        "questions_title": "💬 Questions & Answers",
        "questions_subtitle": "Chat with your data using natural language",
        "question_help": "💭 Type any question about your data - trends, patterns, statistics...",
        "ai_response_title": "🤖 AI Response",
        "additional_insights_title": "💡 Additional Insights",
        "welcome_title": "Welcome to DataVision AI! 🔮",
        "welcome_subtitle": "Your intelligent platform for CSV data analysis",
        "welcome_description": "Transform your data into valuable insights with the power of Artificial Intelligence.",
        "welcome_step1": "📁 **Upload**: Load your CSV file",
        "welcome_step2": "🧠 **Analyze**: Get automatic AI insights",
        "welcome_step3": "📊 **Visualize**: Create intelligent charts",
        "welcome_step4": "💬 **Ask**: Chat with your data",
        "welcome_cta": "Get started by uploading a CSV file using the sidebar!",
        "welcome_ai_title": "Smart AI",
        "welcome_ai_description": "Automatic analysis with powerful insights",
        "welcome_charts_title": "Dynamic Charts",
        "welcome_charts_description": "Interactive and customizable visualizations",
        "welcome_questions_title": "Natural Questions",
        "welcome_questions_description": "Chat with your data in natural language",
        "footer_text": "Built with ❤️ using Google AI and Streamlit | 🔮 DataVision AI",
        "footer_made_with": "Made with ❤️ for intelligent data analysis",
        "generate_ai_help": "🚀 Click to generate the selected chart using AI",
    }
}

# Default language
DEFAULT_LANGUAGE = "pt_BR"