# Language dictionaries for the CSV AI Parser application

# Available languages
LANGUAGES = {
    "pt_BR": {
        "app_title": "🔮 DataVision AI - Análise Inteligente de Dados",
        "app_description": """
        **DataVision AI** é sua plataforma inteligente para análise avançada de dados CSV.
        Transforme seus dados em insights valiosos com o poder da Inteligência Artificial.
        Faça upload de um arquivo CSV e descubra padrões ocultos nos seus dados.
        """,
        "language_selector": "Idioma",
        "file_uploader": "Escolha um arquivo CSV",
        "file_details": "Detalhes do arquivo",
        "filename": "Nome do arquivo",
        "filetype": "Tipo do arquivo",
        "filesize": "Tamanho do arquivo",
        "processing": "Processando seu arquivo CSV... Por favor, aguarde.",
        "error_invalid_file": "Por favor, faça upload de um arquivo CSV válido com a estrutura esperada: 31 colunas incluindo Time, V1-V28, Amount e Class.",
        "success_message": "Arquivo processado com sucesso!",
        "data_preview": "Visualização dos Dados",
        "ask_questions": "Faça Perguntas Sobre Seus Dados",
        "enter_question": "Digite sua pergunta:",
        "processing_query": "Processando sua pergunta...",
        "response": "Resposta",
        "additional_insights": "Insights Adicionais",
        "upload_prompt": "Por favor, faça upload de um arquivo CSV para começar.",
        "footer": "Desenvolvido com Google AI e Streamlit | 🔮 DataVision AI",
        "api_key_error": "Por favor, configure sua GEMINI_API_KEY em um arquivo .env",
        "generating_analysis": "Gerando análise inicial... Por favor, aguarde.",
        "analyzing_data": "Analisando dados para sugestões de gráficos...",
        "graph_error_info": "Por favor, tente um tipo de gráfico diferente ou verifique o formato dos seus dados.",
        "initial_analysis": "Análise Inicial",
        "records_analysis": "Análise de Registros",
        "total_records": "Total de Registros",
        "regular_transactions": "Transações Regulares",
        "fraudulent_transactions": "Transações Fraudulentas",
        "time_analysis": "Análise de Tempo",
        "total_time_period": "Período Total de Tempo",
        "amount_analysis": "Análise de Valores",
        "regular_transactions_heading": "Transações Regulares",
        "fraudulent_transactions_heading": "Transações Fraudulentas",
        "total_amounts": "Valores Totais",
        "min_amount": "Valor Mínimo",
        "max_amount": "Valor Máximo",
        "avg_amount": "Valor Médio",
        "regular_total": "Total Regular",
        "fraudulent_total": "Total Fraudulento",
        "visualization": "Visualização",
        "select_graph": "Selecione um gráfico para exibir:",
        "generate_graph": "Gerar Gráfico",
        "generating_graph": "Gerando gráfico...",
        "fraud_distribution": "Distribuição de Fraudes vs Regulares",
        "amount_distribution": "Distribuição de Valores",
        "time_series": "Transações ao Longo do Tempo",
        "related_questions_warning": "Por favor, faça perguntas relacionadas ao arquivo CSV importado e seus dados.",
        "manual_chart_option": "Ou digite manualmente o tipo de gráfico desejado:",
        "manual_chart_placeholder": "Ex: histograma da coluna Amount, gráfico de dispersão entre X e Y...",
        "generate_custom_graph": "Gerar Gráfico Personalizado",
        "custom_chart_validation_error": "Por favor, descreva o tipo de gráfico que você deseja gerar.",
        "chart_generation_options": "Opções de Geração de Gráficos"
    },
    "en_US": {
        "app_title": "CSV AI Parser",
        "app_description": """
        This application uses AI to analyze CSV files and answer questions about the data.
        Upload a CSV file and ask questions to get insights from your data.
        """,
        "language_selector": "Language",
        "file_uploader": "Choose a CSV file",
        "file_details": "File Details",
        "filename": "Filename",
        "filetype": "File type",
        "filesize": "File size",
        "processing": "Processing your CSV file... Please wait.",
        "error_invalid_file": "Please upload a valid CSV file with the expected structure: 31 columns including Time, V1-V28, Amount, and Class.",
        "success_message": "File processed successfully!",
        "data_preview": "Data Preview",
        "ask_questions": "Ask Questions About Your Data",
        "enter_question": "Enter your question:",
        "processing_query": "Processing your query...",
        "response": "Response",
        "additional_insights": "Additional Insights",
        "upload_prompt": "Please upload a CSV file to get started.",
        "footer": "Powered by Google AI and Streamlit",
        "api_key_error": "Please set your GEMINI_API_KEY in a .env file",
        "generating_analysis": "Generating initial analysis... Please wait.",
        "analyzing_data": "Analyzing data for chart suggestions...",
        "graph_error_info": "Please try a different chart type or check your data format.",
        "initial_analysis": "Initial Analysis",
        "records_analysis": "Records Analysis",
        "total_records": "Total Records",
        "regular_transactions": "Regular Transactions",
        "fraudulent_transactions": "Fraudulent Transactions",
        "time_analysis": "Time Analysis",
        "total_time_period": "Total Time Period",
        "amount_analysis": "Amount Analysis",
        "regular_transactions_heading": "Regular Transactions",
        "fraudulent_transactions_heading": "Fraudulent Transactions",
        "total_amounts": "Total Amounts",
        "min_amount": "Minimum Amount",
        "max_amount": "Maximum Amount",
        "avg_amount": "Average Amount",
        "regular_total": "Regular Total",
        "fraudulent_total": "Fraudulent Total",
        "visualization": "Visualization",
        "select_graph": "Select a graph to display:",
        "generate_graph": "Generate Graph",
        "generating_graph": "Generating graph...",
        "fraud_distribution": "Fraud vs Regular Distribution",
        "amount_distribution": "Amount Distribution",
        "time_series": "Transactions Over Time",
        "related_questions_warning": "Please ask questions related to the imported CSV file and its data.",
        "manual_chart_option": "Or manually enter the desired chart type:",
        "manual_chart_placeholder": "Ex: histogram of Amount column, scatter plot between X and Y...",
        "generate_custom_graph": "Generate Custom Graph",
        "custom_chart_validation_error": "Please describe the type of chart you want to generate.",
        "chart_generation_options": "Chart Generation Options"
    }
}

# Default language
DEFAULT_LANGUAGE = "pt_BR"